### ISSUE TITLE
Epic: NSwag v12

### ISSUE THREAD

**Issue by RSuter** [RSuter/NSwag#984]
Next major version v13: https://github.com/RSuter/NSwag/issues/1700

**Breaking changes:**

There are breaking changes but most of them can be fixed by using the renamed method or change a setting. 

Settings

- **The default settings have been updated**, see PR #1719 for details
    - When using an nswag.json file, the old settings are retained and this is not a breaking change.
    - When using the CLI directly (e.g. swagger2csharp command) then these defaults **may be a breaking change** and the previous settings have to be set explicitely to generate the previous output.

Runtime (CLI, NPM, NSwagStudio)

- **Default runtime set to NetCore21 (before WinX64)**
    - Change this in NPM command line with the `/runtime:WinX64` parameter
    - The WinX86/WinX64 command line ASP.NET Core dependencies have been upgraded to 2.1.x (#1696)
    - Upgrade ASP.NET Core dependencies (x64/x86) (#1696) 
    - For more information, see https://github.com/RSuter/NSwag/wiki/Assembly-loading

NSwag.AspNetCore (middlewares)

- **The API of the ASP.NET Core middlewares have been changed** (easy fix)
    - All public **and** not obsolete methods are now completely based on [AspNetCoreToSwaggerGenerator](https://github.com/RSuter/NSwag/wiki/AspNetCoreToSwaggerGenerator)
        - The old [WebApiToSwaggerGenerator](https://github.com/RSuter/NSwag/wiki/WebApiToSwaggerGenerator) based methods are still available but deprecated and will be removed in v13 (#1700)
    - `AddSwaggerDocument()/AddOpenApiDocument()`
        - Document configuration moved to `AddSwaggerDocument(configure)` in `ConfigureServices()` (before in `UseSwaggerWithApiExplorer()`)
    - `UseSwaggger()`
        - `UseSwagggerWithApiExplorer()` is now just `UseSwagger()` in `Configure()`
        - `SwaggerRoute` renamed to `Path` (#1728)
    - `UseSwaggerUi*()`
        - Web UI methods now **only register the UI** and do not serve `swagger.json` anymore (use an additional call to `UseSwagger()`)
        - `UseSwaggerUi3WithApiExplorer()` no longer exists, use `UseSwagger()` and `UseSwaggerUi3()` in `Configure()`
        - `UseSwaggerReDoc()` renamed to `UseReDoc()`
        - `SwaggerUiRoute` renamed to `Path` (#1728)
        - `SwaggerRoute` renamed to `DocumentPath` (#1728)
    - For more information, see PR #1655 and wiki at https://github.com/RSuter/NSwag/wiki/AspNetCore-Middleware
        - Use `AddOpenApiDocument()`/`AddSwaggerDocument()` directly on services (#1714)
        - Add `IDocumentProvider` service and its implementation (#1678)
            - This is used in the CLI with the new `UseDocumentProvider` setting (enabled by default)
- **API Versioning handling has been improved with breaking changes**
    - The `ApiVersionProcessor` registration and `IncludedVersions` have been removed and replaced by the `ApiGroupNames` setting
        - For more information see PR #1701 or wiki at https://github.com/RSuter/NSwag/wiki/AspNetCore-Middleware
        - Add **ApiGroupNames** setting, remove ApiVersionProcessor and improve api versioning (#1701) 

**Bug fixes and improvements**

Swagger generator

- **Add CreateWebHostBuilderMethod and AspNetCoreEnvironment setting, implement UseDocumentProvider & DocumentName #1655**
    - **UseDocumentProvider** will be enabled by default and generates a document registered with AddSwaggerDocument() in ConfigureServices
        - Select document with the **DocumentName** setting
    - **CreateWebHostBuilderMethod** can be used to define the `CreateWebHostBuilder` method (entry point to load an app)
    - **AspNetCoreEnvironment** changes the ASPNETCORE_ENVIRONMENT env var
- Use SwaggerResponseAttribute.Description with API Explorer, closes #1648
- Add TransformToExternalPath setting (#1728)

CSharp 

- Use header parse, closes #1649
- Handle OpenAPI 3 file response in client generators, closes #1629
- [C# Client] Boolean query parameters are now lowercase (#1711)
- Add support for x-www-form-urlencoded (CSharp) (#1739)

TypeScript

- Fix default reponse handling (TS), closes #1683 
- Only generate the blobToText and throwException if it is needed (#1705)

Other

- Change YAML version to v5.0.1, https://github.com/RSuter/NSwag/commit/1e2baa5dbe1b9e6633f0751b9798c155dab35ad1
- Rename TagSorter -> TagsSorter to match what swagger-ui needs (#1708)
- Fix swagger ui 3 params, closes #1694 
- Use correct operation type, closes #1650 
- Migrate some test projects to use Xunit (#1669)
- **All changes & fixes in [NJsonSchema](http://njsonschema.org) after 9.11.0**
    - Add support for JsonInheritanceAttribute in schema generator (https://github.com/RSuter/NJsonSchema/pull/813) 
    - Add JsonSchemaFlattenAttribute (https://github.com/RSuter/NJsonSchema/commit/c1484a03e864fe086be5fb99a42450196bb1d4ee)
    - Dereference actual type schema (https://github.com/RSuter/NJsonSchema/pull/798)

**Planning**

Epics: 

- [x] New template engine (enabled by default): https://github.com/RSuter/NSwag/issues/263
- [x] Api explorer: https://github.com/RSuter/NSwag/issues/999
- [x] OpenAPI 3.0.0 support (still some problems)
- [x] Change default settings: https://github.com/RSuter/NSwag/pull/1719

Fixed issues: 

- [x] See #1658 : Separately, the registrar currently has a "last one wins" semantic. Not sure we should require distinct DocumentName properties in the initial release. Wouldn't that be a breaking change? (already enabled)
- Also see: https://github.com/RSuter/NJsonSchema/issues/507

**Comment by RSuter** [comment]
New default type settings: 

```csharp
// Client/Controller parameter/response types

ResponseArrayType = "System.Collections.Generic.ICollection";
ResponseDictionaryType = "System.Collections.Generic.IReadOnlyDictionary";

ParameterArrayType = "System.Collections.Generic.IEnumerable";
ParameterDictionaryType = "System.Collections.Generic.IReadOnlyDictionary";

// DTO Properties

DateType = "System.DateTime";
DateTimeType = "System.DateTime";
TimeType = "System.TimeSpan";
TimeSpanType = "System.TimeSpan";

ArrayType = "System.Collections.Generic.ICollection";
DictionaryType = "System.Collections.Generic.IDictionary";
```

**Comment by Bomret** [comment]
I think it ld be good to use `System.DateTimeOffset` for date time types. So you get the UTC offset and thus globally unique dates.

**Comment by RSuter** [comment]
@Bomret good point. We'll check this as soon as the major release is imminent... will still take some time and **changing** the defaults is simple.

**Comment by RSuter** [comment]
Requirements moved to PR: https://github.com/RSuter/NSwag/pull/1719
